Update updater-script to handle uefi.img conditionally

diff --git a/META-INF/com/google/android/updater-script b/META-INF/com/google/android/updater-script
--- a/META-INF/com/google/android/updater-script
+++ b/META-INF/com/google/android/updater-script
@@ -110,7 +110,12 @@ mkdir -p /sdcard/UEFI
 dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="/sdcard/UEFI/uefi.img" bs=1M || { abort "Error copying uefi.img"; }
 dd if="/sdcard/WinInstaller/backup/boot$(getprop ro.boot.slot_suffix).img" of="$WIN_MOUNT_FOLDER/boot.img" bs=16M || { abort "Error copying boot.img in Windows"; }
 dd if="$WIN_MOUNT_FOLDER/installer/pe.img" of="$BASE_PATH/esp" bs=16M || { abort "Error flashing WinPE.img"; }
-dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="$BASE_PATH/boot$(getprop ro.boot.slot_suffix)" bs=1M || { abort "Error flashing uefi on boot partition"; }
+if [ -f "$WIN_MOUNT_FOLDER/installer/uefiboot.img" ]; then
+    UEFI_IMG="$WIN_MOUNT_FOLDER/installer/uefiboot.img"
+else
+    UEFI_IMG="$WIN_MOUNT_FOLDER/installer/uefi.img"
+fi
+dd if="$UEFI_IMG" of="$BASE_PATH/boot$(getprop ro.boot.slot_suffix)" bs=1M || { abort "Error flashing uefi on boot partition"; }
 umount "$WIN_PATH" "$ESP_PATH"
 sleep 1
 print_line =
